modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Death-Knell/issues"

[[mods]]
modId = "deathknell"
version = "26.2.0.0"
displayName = "DeathKnell"
updateJSONURL = "https://updates.blamejared.com/get?n=deathknell&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/death-knell"
logoFile = "logo_deathknell.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Spice up the game with new player death messages."

[[mixins]]
config = "deathknell.common.mixins.json"

[[mixins]]
config = "deathknell.neoforge.mixins.json"

[[dependencies.deathknell]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.deathknell]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deathknell]]
modId = "bookshelf"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deathknell]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

